version: '3.4'

services:
  nodedocker:
    image: nodedocker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
