version: '3.4'

services:
  nodedocker:
    image: nodedocker:0.0.3.RELEASE
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production

    ports:
      - 3000:3000
    networks: 
      - nodedocker
    depends_on: 
      - db
  db:
    image: mongo
    container_name: mongodb
    restart: always
    networks: 
      - nodedocker
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - 27018:27017
    


networks: 
  nodedocker: